# External gems
gems:
#  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

# Site settings
title: "Word Hoard Press"
subtitle: "A Literary Press for Ancient Poems by Modern Writers"
email: "richard.littauer+wordhoardpress@gmail.com"
name:  "Richard Littauer"
description: "A Literary Press for Ancient Poems by Modern Writers"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://wordhoardpress.com" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.png"

# Metadata
# twitter_logo: "assets/twitter_360.png"
# fb_logo: "assets/twitter_360.png"
fb_image_type: "image/png"
fb_logo_width: 360
fb_logo_height: 360

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# # Archive settings (see https://github.com/jekyll/jekyll-archives/)
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layout: 'archive'
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: wordhoardpress

# Google analytics
ga_tracking_id: "UA-4124866-33"

# Category descriptions (for archive pages)
# descriptions:
#   - cat: jekyll
#     desc: "Posts describing Jekyll setup techniques."

  # - cat: dummy
  #   desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@example"                  # (User) Name to display in the footer link
#     url: https://twitter.com/wordhoardpress # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: http://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL
#     
social:
  - name: Twitter
    icon: twitter
    username: "@WordHoardPress"
    url: https://twitter.com/WordHoardPress
    desc: Follow us on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
